### ISSUE TITLE
fragment has no attribute fragments.proj_mesh.verts_list()

### ISSUE THREAD

**Issue by kangx326** [jkxing/DROT#1]
Hi, I'm using pytorch3d to perfrom differentiable rendering.
In \core\PyTorch3DRenderer.py line 34, the code is verts_list = image_fragments.proj_mesh.verts_list()[0][None, ...].
However, the code went wrong and I didn't find proj_mesh in pytorch3d documents.
How can I solve this errors?

**Comment by jkxing** [comment]
Please install the modified PyTorch3D Library according to readme.
